[project]
workDir = "backend"

[phases.setup]
nixPkgs = ["python313", "gcc"]

[phases.install]
commands = [
  "python3.13 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt" 
]

[phases.build]
commands = [
  "python manage.py migrate",
  "python manage.py collectstatic --noinput"
]

[start]
cmd = "gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT"
